### PR TITLE
Allow the createOption function to reject the new option

### PR DESCRIPTION
**Pull request by ph4r05**
I came to a need to block creating of some particular tags so this solution came to my mind.

If user-defined callback `createOption()` returns `null` or `undefined` the option will be rejected / not added.

### CODE REVIEW

**Comment by ph4r05** [comment]
This appears to break the tests. I will take another look.

**Comment by eric-naguras** [comment]
@ph4r05 May I ask why this PR was not honored?
This issue is a breaking problem.

I want my users to confirm when they add a new item to the list, like this:

```
createComposer (newComposer) {   
      console.log('New Composer', newComposer)   
      if (window.confirm(`Not in list.\n\nDo you want to add ?`)) {   
        return {label: newComposer}   
      } else {   
        return null   
      }   
    }
```
But the current version will crash the component.

This PR solves the problem although I would not have an empty if block.
Can you fix this yourself or come up with a better solution.

Cheers.

**Comment by tapanbavaliya** [comment]
i am facing this problem, can anyone tell me the status of this please

**Comment by ph4r05** [comment]
I was not working on this since closing the PR. There was apparently some problem with breaking tests and I decided to take a different way.

Take a look if my fork works for you: https://github.com/ph4r05/vue-select

I used own component: https://github.com/ph4r05/ph4-vue-select

**Pull request closed without merging**
