### PR TITLE
fix(#1679): css file not being exported by package.json

### PR DESCRIPTION
**Pull request by TomYaMee**
This PR fixes issue with #1678 by adding css exports declaration in `package.json`

### CODE REVIEW

**Comment by pilishen** [comment]
@TomYaMee maybe you could push with a dist folder? so that we could install your pull/request directly.
thanks

**Comment by TomYaMee** [comment]
@pilishen I have published my fork on npm, you can install directly with `npm i @tomyamee/vue-select` while we wait for this to be fixed on the main package.

**Comment by pilishen** [comment]
@TomYaMee thanks ~ @sagalbot suprised to see this quick merge, thought it would take days,hah

**Comment by Xaaalera** [comment]
image

**Comment by Xaaalera** [comment]
image
image

**Pull request merged**
