### PR TITLE
Prevent interaction when component is disabled

### PR DESCRIPTION
**Pull request by andywarren86**
- can no longer remove selected items from disabled multiple select by mouse click
- can no longer interact with dropdown via keyboard

### CODE REVIEW

**Comment by andywarren86** [comment]
Fixes issues:
https://github.com/sagalbot/vue-select/issues/210
https://github.com/sagalbot/vue-select/issues/336

**Comment by ThomHurks** [comment]
I was actually thinking about making a PR for this too, but you beat me to it. Nice!

**Comment by andywarren86** [comment]
I had considered removing the close button, but was worried it would cause all of the items to change size and position if the disabled prop was dynamically toggled. Not sure if that is worth worrying about though?

**Comment by ThomHurks** [comment]
I think it's better to leave the remove button for accessibility reasons too. The general practice seems to be to not remove disabled items, so that the impaired user still knows they exist, but through proper use of ARIA attributes knows that the button is disabled and (potentially) for what reason. For regular users it's probably better too to see that the labels are potentially removable, but that the form is just disabled.

**Comment by andywarren86** [comment]
No worries glad I could help!

**Pull request merged**
