### PR TITLE
Fix Dropdown closing abruptly when clicking scrollbar under IE

### LINKED ISSUE #106: In IE, clicking the scrollbar collapses the dropdown
Tested in IE 10, IE 11:

When clicking on the scrollbar of the dropdown menu, the dropdown collapses unexpectedly. See the gif:

vue-select-scrollbar-ie

### PR DESCRIPTION
**Pull request by adi518**
Fixes a long standing issue where the drop-down menu would close abruptly upon clicking its scrollbar under IE11, possibly under IE10 as well.

### CODE REVIEW

**Comment by adi518** [comment]
My fix introduced an annoying bug, where once you click the "no-options" placeholder, it leaves the input untypeable. Fixed it now.

**Comment by pippinsoft** [comment]
@adi518 If you don't want the search to clear and the drop-down to close when you click the "No options" placeholder, you can instead add `@mousedown.prevent.stop` on the `.no-options` `<li>`

**Comment by adi518** [comment]
@pippinsoft That's a feature though. This PR only fixes the bug in IE.

**Comment by taivu** [comment]
any updates on this? are conflicts in `Select.vue` because of version 2.3? (current is 2.4)

**Comment by adi518** [comment]
@sagalbot Take it away. :)

**Comment by Craytor** [comment]
Does this fix non-IE browsers too? Chrome is doing this on Windows as well.

**Comment by adi518** [comment]
@Craytor To my best knowledge, it works as expected under Chrome. The issue would be much prominent otherwise.

**Comment by Craytor** [comment]
@adi518 It doesn't work on Chrome on Windows.

**Comment by adi518** [comment]
@Craytor It certainly does not: https://codepen.io/sagalbot/pen/vxvVPM

**Comment by Craytor** [comment]
@adi518 Very interesting. That one is working fine on chrome, but the one on my site is not working correctly on chrome. Same version and all.

**Comment by adi518** [comment]
@Craytor I guessed so. Just isolate it, see if it's affected by something. Could be another bug otherwise.

**Comment by Jonas-buriti** [comment]
@sagalbot i faced this error, and now i'm using the version on this pull request.
Can you merge it?

@adi518 great man! Thanks

**Comment by Prior99** [comment]
We're also experiencing this problem in our project and this fix would be highly appreciated. Is there any reaso that this is not yet merged? Can I help out with this in some way?

**Comment by adi518** [comment]
Fixed the conflicts. My bad for noticing earlier.

**Comment by TrabacchinLuigi** [comment]
this should definetely be merged

**Comment by adi518** [comment]
This also fixes #474.

**Comment by Prior99** [comment]
@sagalbot Can we help you in any way to get this merged?

**Comment by odrozd** [comment]
Any updates when this issue will be merged?

**Comment by soichih** [comment]
When will v2.5.0 be released on npm?

**Comment by abacram** [comment]
I'm also waiting for v2.5.0, when it's supposed to be released? Thanks!

**Comment by adi518** [comment]
@montananyto-dev It's already fixed by #682.

**Pull request merged**
