### PR TITLE
Support option with disabled property

### PR DESCRIPTION
**Pull request by markselby9**
1, Add support for options with disabled property
2, Add corresponding test case and demo

issue reference: https://github.com/sagalbot/vue-select/issues/104

### CODE REVIEW

**Comment by markselby9** [comment]
https://github.com/sagalbot/vue-select/issues/116

**Comment by adrichey** [comment]
This is great. +1 for merging this request.

**Comment by markselby9** [comment]
@sagalbot 
I've added an 'disabledkey' for the user to define their own key for `disabled`, along with test cases and demo.
Thanks for your tips, it's simple and clear 👍

**Comment by bcreeves** [comment]
Any timeline for when this gets merged and released?

**Comment by Anatakun** [comment]
Same question : When will this be available ? 
I need this for a project, so i'll fork if needed, but it seems i'm not thinking it's really useful and nearly merged into the master.
Thx

**Comment by frontandstart** [comment]
@sagalbot Do need any help with merge this in master branch?

**Comment by frontandstart** [comment]
To anybody that need to use this feature I create [fork](http://github.com/frontandstart/vue-select) and merge this pull request.
Works good, thanks @markselby9 
@sagalbot may be create some branch with fast forward accepted new features that we can test it on live projects and make feedback?

**Comment by noahduncan** [comment]
I'd also love to see this feature merged. Could use it right now! :)

**Comment by Phoxloxley** [comment]
Has anyone looked at this merge conflict recently?  This is a useful feature, I hate to see issues in PRgatory.  Also it is Hacktoberfest right now, this could help resolve this easily.

**Comment by frontandstart** [comment]
Here is I merge it
https://github.com/frontandstart/vue-select/pull/1 in my fork, but probably current master at main repo is ahed of mine, because I did it more than 6 month ago

**Comment by reppair** [comment]
@sagalbot any chance this gets merged soon? It is an useful feature.

**Comment by r3cha** [comment]
> @sagalbot any chance this gets merged soon? It is an useful feature.
It was in 2018 :(
Probably he didn't have time for this

**Comment by doits** [comment]
`:selectable` feels good to me! Is there a timeline when this will be implemented?

**Comment by alxgb** [comment]
Agree that the `:selectable` API sounds pretty good

**Comment by huglester** [comment]
any progress on this?

**Comment by wilian746** [comment]
any progress on this?

**Comment by doits** [comment]
@wilian746 see #921 for an initial implementation - feel free to test and report back your findings (must run `yarn build` though to have it compiled in `dist` folder)

**Comment by jalendport** [comment]
@sagalbot any chance you could cut a new release soon? 🤞 Need this for a project! 🤓

**Pull request closed without merging**
