### PR TITLE
filter-key and filter-callback props

### PR DESCRIPTION
**Pull request by stereosteve**
See https://github.com/sagalbot/vue-select/issues/190 for initial discussion.

### CODE REVIEW

**Comment by stereosteve** [comment]
@sagalbot can you review?

I rebased on master, let me know if that causes any problems.

**Comment by stereosteve** [comment]
Sounds good, no rush to merge.  I'm considering another option:

* If option has `hidden = true` it is not shown
* Emit events when search input changes

Calling code can listen for search change events (or anything else really) and change what options are shown + hidden.  Also will have access to option object so can use extra meta data.

Going to give it a try.

**Comment by stereosteve** [comment]
@sagalbot I tried a few things, but they were too complicated.  I think this PR is good enough.

I renamed `filter-callback` to just `filter`, and swapped the parameters so that the filter value is the first parameter to mimic standard JS filter function.  `option` is passed as 3rd parameter in case you wish to use additional properties of the option for filtering.

Let me know if this looks okay.  I can squash to 1 commit if you prefer.

**Comment by alan-zhang-** [comment]
Hi, can this feature be used for now? I definitely need to stop client side filtering.

**Comment by Snippo** [comment]
I also needed to disable the filter functionality. You can install the pull request with npm like this:
npm i --save-dev sagalbot/vue-select#pull/191/head

**Comment by sdmackay** [comment]
Any news on when this is going to be merged into master?

**Comment by sdmackay** [comment]
@sagalbot Is this PR and #233 doing the same things?

**Pull request closed without merging**
