### PR TITLE
Feature/index prop

### PR DESCRIPTION
**Pull request by SimoTod**
Proposal to solve #122 (Option to specify `id` property / selected key).
A few tests have been added to make sure the pre-existent features won't break when the new one is active.

### CODE REVIEW

**Comment by SimoTod** [comment]
Yeah, no worries. I've been using my version for a project because I needed
the vue model to be synchronised with an object value and it seems alright
but I'm not in a rush (I'll switch back to the official module once it's
ready). Feel free to reword the documentation bit: I wrote it late at night
(I live in UK) and I'm not a native speaker. If you spot something not
right, I'd like to hear your feedbacks. Thanks.

On 18 Jan 2018 21:45, "Jeff" <notifications@github.com> wrote:

Looking good, really dig the attention to detail with the docs and tests.
Going to need a bit of time to contemplate this one - it's a highly
requested feature so just want to make sure we nail the API.

Really appreciate the work here!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sagalbot/vue-select/pull/423#issuecomment-358791796>,
or mute the thread

**Comment by lou** [comment]
I would be very happy to test this feature.Unfortunately I'm not able to make it work.

I tried to used it in my project thanks to the following command:
`yarn add "https://github.com/SimoTod/vue-select#feature/index-prop"`

But It does not use the right library. I suspect it is because the dist/ was not re-builded on the forked repository.
So I tried to build it myself using `yarn build` but it failed with the following error:
```
yarn run v1.3.2
$ node build/build.js
Hash: 97ccbd3f7cb7f9d8a564
Version: webpack 1.15.0
Time: 56ms
            Asset     Size  Chunks             Chunk Names
    vue-select.js  2.04 kB       0  [emitted]  lib
vue-select.js.map  2.31 kB       0  [emitted]  lib

ERROR in vue-select.js from UglifyJs
SyntaxError: Unexpected token: name (VueSelect) [./src/index.js:1,0]
✨  Done in 1.40s.
```
I think the error comes from Babel not used correctly. I'm pretty new to Yarn/Webpack/Babel so I suspect I'm missing something here.

Any help would be much appreciated.

**Comment by SimoTod** [comment]
Hi @lou, 

It's correct. I haven't rebuild the library in my branch following the contribution guidelines.
By the way, that error is usually raised by uglify not using the right preset.
Did you run `yarn install` from the library folder before recompiling it?
It should pull all the dev dependencies you need to recompile the dist folder (in particular babel-preset-es2015 which hopefully will fix your errror).
If it didn't work for you, you can now try my master branch where I've just committed the recompiled dist folder so you should be able to import the library as usual without any additional work. 

I hope this will help

**Comment by lou** [comment]
Hi @SimoTod,
Yes I forgot to say it but I did run `yarn install` before `yarn build`
So I will try your master branch  and let you know.

Thank you a lot,

**Comment by lou** [comment]
@SimoTod It works like a charm.
Great work and thank you!

**Comment by NanoDev777** [comment]
@SimoTod How can I implement your solution? at the moment I have made this example of the documentation itself ...  https://codepen.io/sagalbot/pen/Kqxbjw what changes should I make to be able to stay with only the id in the data of my model and not the whole object

**Comment by SimoTod** [comment]
Hi @NanoDev777 ,
The PR hasn't been merged yet because sagalbot is writing tests and documentation for the new feature. For this reason you can't currently use it with the official package. 
If you want to try it in advance, you can require my branch using `yarn add "https://github.com/SimoTod/vue-select#master"` then change the tag to `<v-select v-model="selected" :options="options" index="id"></v-select>`. 
However, I'm not going to maintain my branch since it would be a duplicate of Jeff's work so, as soon as he merge the PR, I suggest you switch back to the official package.

**Comment by SimoTod** [comment]
Hi @sagalbot ,

Sorry to bother you. While I was playing with the codepen NanoDev7777 mentioned, I've just realised that `isValueEmpty` doesn't work as expected when keys are numbers instead of a strings.
Despite of the value being selected, the function still returns true so the search input goes to 100%. (E.g. https://codepen.io/SimoTod/pen/zROqEV).

It doesn't look like a regression since that thing already happens using the previous release with an array of integers as options as you can see at https://codepen.io/SimoTod/pen/zROBNB .

Obviously it will be more evident once the feature is released because I expect several people working with numeric IDs which may be integers rather than strings.

The reason for this bug is line 1064 where the function returns `this.mutableValue.length` assuming that `this.multiple` is true. It works with strings because they have a length property returning the number of characters but it doesn't work with integers.

```
isValueEmpty() {
  if (this.mutableValue) {
    if (typeof this.mutableValue === 'object') {
      return !Object.keys(this.mutableValue).length
    }
    return !this.mutableValue.length
  }
  return true;
},
```
I think the above should be 
```
isValueEmpty() {
  if (this.mutableValue) {
    if (typeof this.mutableValue === 'object') {
      return !Object.keys(this.mutableValue).length
    }
    if (this.multiple) {
      return !this.mutableValue.length
   }
   return true // If not multiple or object and it passed the initial if, the value is never empty (as per JS specification, an empty string would return false in the first if)
  }
  return true;
},
```

Also, I noticed there are some conflicts in the documentation due to some PR you merged recently. Do you want me to fix the conflict or can you have a look youself?

Let me know your though, thanks.
Simone

**Comment by gthuo** [comment]
@sagalbot , the feature is live now? Waiting for it like..!

**Comment by dmitov** [comment]
Any news on this! It's a MUST feature :+1:

**Comment by dmitov** [comment]
@sagalbot Keep in mind that `value` property is reserved in order for `v-model` to work. I'd suggest that we keep the `index` property name.

**Comment by SimoTod** [comment]
Hi @sagalbot, how are you getting on with the review? I'm asking because my project is about to go live and I wanted to remove my custom dependencies as soon as possible. I can help out with renaming the prop, if you are busy (I knew that 'value' would have been a better name, but I didn't want to add a BC). Let me know.

**Comment by sylfel** [comment]
What about this review ? do you think it will be merged soon ?

**Comment by dmitov** [comment]
Any news on this?

**Comment by yuwong** [comment]
this would make life a lot easier, we are working around this but it is not ideal...

**Comment by mohd-isa** [comment]
any plans to merge this soon?

**Comment by gthuo** [comment]
I'm convinced @sagalbot and team are working so hard to continue improving this tool. I just desire to know if they can let us know **when** we can expect this to be fully implemented...

**Comment by mauricioaznar** [comment]
When can we get this feature?.

**Comment by dmitov** [comment]
YAYY!! :confetti_ball: :confetti_ball: :confetti_ball:

**Comment by dashty94** [comment]
Any updates on this feature? When are we able to use it?

**Comment by NanoDev777** [comment]
@SimoTod 
sorry for the question, I would like to know what the fusion is?

**Comment by SimoTod** [comment]
Hi @NanoDev,

The PR has been merged to master but a new release hasn't been tagged yet so the feature is not available at the minute.

Simone 

Cc @dashty94

**Comment by moyvera** [comment]
oh my gooooood!! haha here we go !!!

Thanks guys !

**Comment by dennbagas** [comment]
Can you provide example to get the value instead of the text? Can you put this in hte documentation?

**Pull request merged**
