### PR TITLE
Initial fix for issue 292.

### PR DESCRIPTION
**Pull request by vitamink**
Fixes issue #292, specifically as described by @htunnicliff.

### CODE REVIEW

**Comment by vitamink** [comment]
Please ignore this while I investigate an issue.

**Comment by vitamink** [comment]
Hello again.

It's been tested with single and multi select.
I've also tested it with simple (string) value arrays, and `{value: 'foo', label: 'bar'}` arrays.
Lastly, I tested it with different label names such as: `{value: 'foo', myLabel: 'bar'}`, with the Label= override, and that works.

I hope this is all good. I'd be happy to hear any comments/bugs. Otherwise, I think this can be merged without issue.

Thanks.

**Comment by tspesh** [comment]
Any updates on this??

**Comment by vitamink** [comment]
I recognise that this is effectively a breaking change. To my mind the existing behavior of this component is incorrect, in that the whole point of the `value` property is that it contain a value, and not the object from which the value was derived.

@sagalbot Perhaps this needs some discussion? I may have missed the point entirely, and there is a very easy way to achieve the desired behavior.

**Comment by vitamink** [comment]
Yes, I noticed the existence of `label`, but not `value`.

Would you be happier if a `value` property was added to the component, and if null, then the current behavior would apply. If not null, then the object[value] would be used.

That would make it optional, and not break any existing code...

**Pull request closed without merging**
