### PR TITLE
Add value property

### PR DESCRIPTION
**Pull request by baranovxyz**
Currently it is not possible to get just values from options objects.
This PR fixes it by adding prop 'valueProp' which access options objects properties.

### CODE REVIEW

**Comment by ddzobov** [comment]
I think that add it to docs extremely important 😊

**Comment by agonzalez0515** [comment]
Would really appreciate this documentation! I don't see the value prop being used in that codepen.

**Comment by dbarrington** [comment]
I expected value to work in this case too, but adding index prop worked for my object. 

```
<v-select maxHeight="200px" v-model="form.target_id" index="id" label='name' :options="targets" >
</v-select>
```

**Comment by geri777** [comment]
The index property worked for me:

`<v-select v-model="vsel" index="value" label="label" :options="[{value:0, label:'Hello']">`

**Pull request closed without merging**
