### PR TITLE
V4: Slot Overhaul, Optional Renderless Component

### LINKED ISSUE #78: Option groups
Hello!

Would you please to add something like `<optgroup/>`?

### LINKED ISSUE #558: Slot for title, i.e., line before list of options
I have a need to be able to add a title to the list of options, that is, when user clicks on drop down trigger which displays list of options, I want to be able to add custom html to the top. In my case, that html is supposed to display a message when there are more than 25 items in the list, that they should type more characters to narrow down the search list.

### LINKED ISSUE #632: Bind search text to option slot
If a user wanted to highlight the matching search text of a given option, right now the `search` text would have to be saved in the parent component using the `@search` event. Binding the `search` text would solve this.

Additionally, `(typeof option === 'object')?option:{[label]: option}` is called in a number of places, and should be consolidated. 

- [ ] move slot scope bindings to computed props
- [ ] pull `(typeof option === 'object')?option:{[label]: option}` to a method
- [ ] add `search` to the `option` slot (and maybe all slots?)

---
Related #576

### LINKED ISSUE #685: vs actions as (scoped) slots
Howdy, thanks for the time and effort to make this :) I (gladly) heard about the `renderless mode` planned for v3 💥 but while that doesn't come out, what do you think about passing elements to actions (clear and toggle icon) as slots?

At the moment we rely on `.clear` selector (with high specificity) to style the button and on css trickery to "design" the Chevron toggle. At some cases would be nice to pass custom elements/components such as buttons or icons (svg). I've did some playing at my fork and this might be simple to implement. 

Let me know if still interesting for the current release, it would look something like this:

```HTML
 <v-select placeholder="default" :options="options" :showClearButton="true">
   <MyButton
    slot="clear-button"
    slot-scope="{showClearButton, clearSelection}"
    @click="clearSelection"
    v-if="showClearButton"
  >clear</MyButton>

 <MyOwnChevronSvgIcon slot="open-indicator" data-vs-toggle />
</v-select>
```
Note the data-vs-toggle selector, since (as far as i my vue knowledge goes) we can't pass refs through slot scope.

```JSX
<!-- source -->
...
<div class="vs__actions">
  <slot
    name="clear-button"
    :showClearButton="showClearButton"
    :clearSelection="clearSelection"
    :disabled="disabled"
  >
    <button
      v-show="showClearButton"
      :disabled="disabled"
      @click="clearSelection"
      type="button"
      class="clear"
      title="Clear selection"
    >
      <span aria-hidden="true">&times;</span>
    </button>
  </slot>

  <span
    v-if="!noDrop"
    ref="openIndicator"
    role="presentation"
    :class="{'open-indicator': !$slots['open-indicator'] || $slots['open-indicator'] === ''}"
  >
    <slot name="open-indicator" />
  </span>
</div>
 ...
/**
* Toggle the visibility of the dropdown menu.
* @param  {Event} e
* @return {void}
*/
toggleDropdown(e) {
  if (... || e.target.hasAttribute("data-vs-toggle") {
    
```

### LINKED ISSUE #688: How to create a separator?
I am trying to figure out how to create a separator within a vue-select list. I have tried using custom template, although visually I can style it like a separator, but one can click and select it, which is not standard behavior of a normal separator.

Any idea? Thanks!

### LINKED ISSUE #887: Add new slot as container of options
**Is your feature request related to a problem? Please describe.**
I need to implement Vue perfect scrollbar in the dropdown of vue-select, but it currently doesn't support slot which would behave as container of all slots.

**Describe the solution you'd like**
Add new slot as container all options

### LINKED ISSUE #953: closeOnSelect dynamic props
some options props  is ['a', 'b', 'c', 'more']
if i select "more" i call server to more list and change close on select props true -> false.
but close on select props not working first and second click working.
how can i change close on select props immediately?
i find some interceptor close select but i can't find this option..

### LINKED ISSUE #1004: Table stype for items
Please add a feature to let us show items inside a data grid (table) with headers
at least you can add a slot to get table headers and we can put <tr> tags inside option
or if you get us the index in option slot we can just add header befor first index.
thanks

### PR DESCRIPTION
**Pull request by sagalbot**
## Options Slot

Moves the `option` slot up one level higher. This allows the user much more flexibility when it comes to event handling, display, and functionality. When implemented, it also requires the user to bind events and attributes to elements within the slot manually:

```html
    <v-select :options="options">
      <template v-slot:option="{ option, attributes, events }">
        <li v-bind="attributes" v-on="events">{{ option.label }}</li>
      </template>
    </v-select>
```

Having the slot pulled up one level opens up some new possibilities. For example, you could add pagination directly into the dropdown:

```vue
<template>
  <div id="app">
    <v-select :options="options">
      <template v-slot:option="{ option, attributes, events }">
        <li v-if="option.label === 'pagination'">
          <button @click="offset -= 10">Prev</button><button @click="offset += 10">Next</button>
        </li>
        <li v-else v-bind="attributes" v-on="events">{{ option.label }}</li>
      </template>
    </v-select>
  </div>
</template>

<script>
export default {
  data: () => ({
    countries: [ /* list of countries */ ]
    offset: 0,
    limit: 10,
  }),
  computed: {
    options () {
      return [...this.countries.slice(this.offset, this.limit + this.offset), 'pagination'];
    },
  },
};
</script>
```

pagination

## Renderless

An optional renderless component is provided. The renderless component has no template by default, and uses a render function. The render function is a single scoped default slot, with all of the data, props, methods, and computed properties of the component bound to the slot. This allows for totally customized implementations:

```html
<renderless multiple :options="options" v-slot="select">
  <input
    v-bind="select.scope.search.attributes"
    v-on="select.scope.search.events"
    placeholder="Search for a Country"
  >

  <div class="options">
    <ul>
      <li>Selected</li>
      <li v-for="selected in select.scopedValues">
        <button @click="select.deselect(selected)">
          <span>-</span> {{ selected.label }}
        </button>
      </li>
    </ul>

    <ul>
      <li>Available</li>
      <li v-for="option in select.scopedOptions">
        <button v-bind="option.attributes" @click="select.select(option)">
          <span>+</span> {{ option.label }}
        </button>
      </li>
    </ul>
  </div>
</renderless>
```

Nov-01-2019 11-39-13

---

# Breaking Changes to Document

- [ ] child components have been pulled up a level
   - Does deselect need to be implemented as a functional component?
- [ ] slot signature changes

---

Closes #953 
Closes #685
Closes #1004
Closes #78
Closes #558 
Closes #632
Fixes #688 
Closes #887

### CODE REVIEW

**Comment by pranavkumar389** [comment]
Can we fasten the process to get this merge? I am waiting for this feature.

**Comment by jd1378** [comment]
I think this also solves [my issue](https://github.com/sagalbot/vue-select/issues/1039)

**Comment by gg4u** [comment]
Is the component <renderless> part of last version of https://vue-select.org/ ? How to import it (e.g. import renderless from 'vue-select' ) ? 
Could you show the above example https://github.com/sagalbot/vue-select/pull/977#issue-334603088 on a codepen ? 
I am looking for examples to flexibly render lists of options, not necessarily as a dropbox, and possibility to group them.

**Comment by doutatsu** [comment]
No updates on this work for awhile - any ETA at all for this?

**Pull request closed without merging**
