### PR TITLE
Add select on tab option and example

### PR DESCRIPTION
**Pull request by kball**
Implements #554 by allowing users to specify if they want hitting the 'tab' key to select the current option from the dropdown.

### CODE REVIEW

**Comment by kball** [comment]
@sagalbot ok backed out that change, back to default `false`

**Comment by kball** [comment]
ping @sagalbot any update on this?

**Comment by ebiedcs** [comment]
Hello, any update on this request ? I really need this feature :)

**Comment by ebiedcs** [comment]
#555 @sagalbot  any plans for merging this feature ?!

**Pull request merged**
