### PR TITLE
Fix for #430 Narrow Select Width Display Bug

### PR DESCRIPTION
**Pull request by bzarzuela**
Fixes a display bug I encountered in my project where I had long options on a narrow select width. With this, the premature wrapping to the next line as well as the height restricted silver background on a selected tag is fixed.

### CODE REVIEW

**Comment by bzarzuela** [comment]
I see. Okay, I’m going to work on these side-effects. I’ll take that
approach and have the input automatically resize to the width of the text.
I think a computed property would do it.

**Comment by pippinsoft** [comment]
Maybe this? `:style="{ width: isValueEmpty ? '100%' : (multiple ? 'auto' : '1px') }"`

**Comment by mkudenko** [comment]
@sagalbot Can this be merged please?

**Comment by pippinsoft** [comment]
This seems to work: `:style="{ width: isValueEmpty || search ? '100%' : '1px' }"`

**Comment by fractalocity** [comment]
It looks like this got merged, but how do you get this to work. I tried  `:style="{ width: isValueEmpty || search ? '100%' : '1px' }"` and that didn't seem to do anything. I tried just forcing the style width to 100% or 1px also and that didn't seem to make a difference.

**Comment by fractalocity** [comment]
@pippinsof are you sure that style modification worked for you? It doesn't not work for me.
`<v-select :style="{ width: isValueEmpty || search ? '100%' : '1px' }" ... >`

**Comment by pippinsoft** [comment]
@fractalocity It does work for me, although I have quite a few modifications, so it could be that I missed something. Are you changing the file under `node_modules`? That won't work. You need to copy it to your source (or explicitly include the `Select.vue` file) and hard refresh to get see changes in your browser.

**Comment by pippinsoft** [comment]
@fractalocity Sorry, I think I see what's causing the confusion. My comment is in reference to this line:

https://github.com/sagalbot/vue-select/blob/546b27d7d21e77680b47efe50d8873237f7a775f/src/components/Select.vue#L344

Which is changed in the PR.

**Comment by fractalocity** [comment]
@pippinsoft You are correct. I was hoping I could modify the input object's style but using the v-select ':style=' property.

I gave your suggestion another shot and still failing. 
This probably won't be a great question, but what do you mean by 'copy it to your source, or explicitly include the Select.vue file)'? 

I tried adding the Select.vue to my project directory (project/src/components) and then added the mixins folder that Select.vue needed to my src directory (project/src). When I did this I got a lot of error messages so that is probably not what you meant in your suggestion:
image

I also tried importing the Select.vue file within the nodes_mode directory which also did not work:
image

**Comment by fractalocity** [comment]
@bzarzuela were you ever able to get the input width to function like you wanted it to?

**Comment by bzarzuela** [comment]
@fractalocity yes, but I haven't found any time yet to modify it so that it would address the issues @sagalbot raised. I will try to do so next weekend.

**Comment by pippinsoft** [comment]
@fractalocity Looks like you're on the right track. Something's upset about tabs -- try swapping them for spaces. (I saw another PR that had this change.)

**Comment by fractalocity** [comment]
@pippinsoft thanks for the guidance. I'll tinker with it a bit more

**Comment by fractalocity** [comment]
@bzarzuela thanks for the reply. I can try tinkering around with it until then.

**Comment by eriknygren** [comment]
I believe I fixed the issue here without raising any side effects on the multiple select mode, would appreciate your feedback https://github.com/sagalbot/vue-select/pull/512 @fractalocity @bzarzuela, cheers.

**Comment by xavism** [comment]
@fractalocity you can do it this way, but you should import the index.js inside the src folder. There the component is exported to use 😄 

image

**Comment by stevenharman** [comment]
I think we can close this one; it’s been superseded by #512.

**Pull request closed without merging**
