### PR TITLE
prevent enter on keydown

### LINKED ISSUE #847: Enter submits the form
**Describe the bug**
When enter is pressed, the form submits. This makes searchable tagging difficult. It looks like the problem is its prevented on `keyup` instead of `keydown`. I saw #249, I'm not sure if it was intentional in v3 or was just missed. 

**To Reproduce**
1. Go to [codepen](https://codepen.io/udimitri/pen/zXayaw)
2. Focus the select and click enter.

**Expected behavior**
Only the value should be selected, the form should not be submitted. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73.0.3683.103

### PR DESCRIPTION
**Pull request by udimitri**
Fixes #847

### CODE REVIEW

**Comment by taylormaguire** [comment]
@udimitri I tried your fix but didn't work for me. form still submits. i'm using the select component inside of an html form though, the form is not in my vue component itself.

**Comment by ziming** [comment]
Hope this gets merged!

**Comment by jbbr** [comment]
This PR fixes the issue for me, thanks! Hope this gets merged soon.

For the meantime: I've added this fix to a branch of my own and also added a prebuild dist js/css to the repo. So it can directly be used with npm/yarn:
```bash
yarn add https://github.com/jbbr/vue-select.git#hotfix/keydown
# untested, but should also work with npm
npm install --save https://github.com/jbbr/vue-select.git#hotfix/keydown
```

**Comment by WayneHiller** [comment]
This needs to get merged soon

**Pull request closed without merging**
