### PR TITLE
Add options to enable/disable deselect when repeat select an option

### PR DESCRIPTION
**Pull request by msyesyan**
https://github.com/sagalbot/vue-select/issues/180

as the issues I said, I just want to keep the selected option when I repeat select the same options

toggleselectoption

### CODE REVIEW

**Comment by giovanniorigins** [comment]
+1

**Comment by msyesyan** [comment]
@sagalbot  can you looks this branch?

**Comment by krystalcampioni** [comment]
+1

**Comment by emil14** [comment]
+1

**Comment by ishanAhuja** [comment]
+1

**Comment by adi518** [comment]
Looks [here](https://github.com/sagalbot/vue-select/issues/180#issuecomment-324627566) for a workaround.

**Comment by alexon1234** [comment]
+1

**Comment by ImpossivelPT** [comment]
Hi there @sagalbot is it possible to merge this PR? It will solve a big issue that I have, thanks man!

**Comment by odedglas** [comment]
+1

**Comment by vsorrokin** [comment]
So? Seems like need to fork(

**Comment by vsorrokin** [comment]
Really need this

**Comment by vsorrokin** [comment]
Forked repo with deselectOnSameValue param (default false) https://github.com/vsorrokin/vue-select

**Comment by ImpossivelPT** [comment]
Hi @sagalbot, should this feature (not being able to deselect the previous selected option), be visible on this example? https://codepen.io/sagalbot/pen/aEjLPB

this uses: https://unpkg.com/vue-select@latest

But i'm able to deselect : \

**Comment by ImpossivelPT** [comment]
Oh ok, good to know I was thinking that something was wrong :)

Thanks!

Em 26/01/2018 21:31, "Jeff" <notifications@github.com> escreveu:

**Comment by SerNeo** [comment]
Hi, is there any new when this issue will be released ?

**Pull request closed without merging**
